name: Use .NET Core
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]  
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: '5.0.x'
    - name: Publish .NET Core project
      run:  dotnet publish Country_Blazor.csproj -c Release -o release --nologo
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: InterviewCountry
        FOLDER: release/wwwroot
